language: cpp
sudo: required
dist: xenial

env:
  global:
    - OMP_NUM_THREADS=4

compiler:
  - gcc
  - clang

before_install:
# Intel OpenMP (for building with clang)
  - sudo apt-get install -y libiomp-dev
# Intel MKL
  - curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | sudo apt-key add -
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt-get update -qq
  - sudo apt-get install -y intel-mkl-64bit-2017.4-061
# Eigen
  - sudo apt-get install -y libeigen3-dev
# Google Test
  - sudo apt-get install -y libgtest-dev
  - cd
  - mkdir gtest-build; cd gtest-build/
  - cmake /usr/src/gtest/
  - make -j4
  - sudo cp *.a /usr/local/lib/
# Ceres Solver
  - sudo apt-get install -y libgoogle-glog-dev
  - cd
  - git clone --depth=1 https://ceres-solver.googlesource.com/ceres-solver
  - cd ceres-solver
  - mkdir build; cd build/
  - cmake .. -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_LIBRARY_PATH=/opt/intel/mkl/lib/intel64 -DCXSPARSE=OFF -DEIGENSPARSE=OFF -DGFLAGS=OFF -DSCHUR_SPECIALIZATIONS=OFF -DSUITESPARSE=OFF
  - make -j4
  - sudo make install
# FLANN
  - sudo apt-get install -y libflann-dev
# Boost
  - cd
  - wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2
  - tar xfj boost_1_65_1.tar.bz2
  - cd boost_1_65_1
  - ./bootstrap.sh
  - ./b2 link=static --with-program_options install -d0 -j4 --prefix=.

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake .. -DBOOST_ROOT=~/boost_1_65_1 -DCMAKE_BUILD_TYPE=Release
  - make -j4
  - ctest -VV
